### ISSUE TITLE
앞서 만들었던 unit test 를 추가해주세요

### ISSUE THREAD

**Issue by jmhwang** [wkim7015/Back_up_0.1#1]

**Comment by wkim7015** [comment]
메인 은 작성중입니다. 나머지들을 올렸고, 주소들은 곧 할당해서 예제로 올릴 예정입니다.

**Comment by wkim7015** [comment]
메인 은 작성중입니다. 나머지들을 올렸고, 주소들은 곧 할당해서 예제로 올릴 예정입니다.
