### ISSUE TITLE
TEST 폴더의 테스트를 어떻게 실행하나요?

### ISSUE THREAD

**Issue by jmhwang** [wkim7015/Back_up_0.1#3]
테스트 실행방법을 알려주세요

**Comment by jmhwang** [comment]
`http://stackoverflow.com/questions/7505988/importing-from-a-relative-path-in-python` 의 `EDIT Nov 2014 (3 years later):` 부분이 도움이 될 것 같습니다.

**Comment by wkim7015** [comment]
테스트 실행방법은 README 와 각각 파일 안에 간단한 포맷을 적어 놓았습니다. 

그리고 http://stackoverflow.com/questions/7505988/importing-from-a-relative-path-in-python 의 EDIT Nov 2014 (3 years later): 부분 에 의하여 새로운 방법으로 시도 하였습니다. 그러나 지금 제가 가진 파일들은 패키지에 들어가있는게 아닌 모듈이기 때문에 **package** 를 첨가 하여 이름을 부여하거나( 동시에 테스트 파일들도 같이 하는것도 가능합니다)테스트로  바깥 스크립트를 써서(e.g. nosetests) 다른 클래스로 연결하여 하는 방법이 있습니다.  아니면 위에것을 냅두고 실행파일안에 **main** 을 작성한다음 아래의 명령어를 사용하는 방법도 있습니다. 미래의 편리성을 가정할떄 어떤 방법으로 하는게 가장 좋을까요?

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(**file**), '..')))

package 으로 할때

장점:  다른 파일에서 고유 이름 때문에 다시 불러올수 있습니다.
단점: 이 파일은 그 안에 존재 하여만 합니다. 다른 디렉토리에 있을시 사용이 불가능할수도 있습니다.

main 으로 할떄

장점: 어디 디렉토리에 있든 사용이 가능합니다.

단점: 다른 파일에서 부를시 relative import는 사용이 불가능 합니다. 파일을 복사해서 그 디렉토리에 사용가능 할 수 도 있습니다.

위에 있는 정보는 아래를 토대로 작성하였습니다.

http://stackoverflow.com/questions/11536764/attempted-relative-import-in-non-package-even-with-init-py

**Comment by wkim7015** [comment]
테스트 파일은 external script 라 패키지 사용이 불가능합니다.

Reference: http://stackoverflow.com/questions/22942650/relative-import-from-init-py-file-throws-error

커밋이름:477d496

**Comment by jmhwang** [comment]
```
C:\Users\phdhwang\Desktop\Back_up_0.1>python TEST\merged.py
Traceback (most recent call last):
  File "TEST\merged.py", line 2, in <module>
    from TESTcopy_function import*
  File "C:\Users\phdhwang\Desktop\Back_up_0.1\TEST\TESTcopy_function.py", line 4, in <module>
    from copy_function import *
ImportError: No module named copy_function

C:\Users\phdhwang\Desktop\Back_up_0.1>cd TEST

C:\Users\phdhwang\Desktop\Back_up_0.1\TEST>python merged.py
Traceback (most recent call last):
  File "merged.py", line 2, in <module>
    from TESTcopy_function import*
  File "C:\Users\phdhwang\Desktop\Back_up_0.1\TEST\TESTcopy_function.py", line 4, in <module>
    from copy_function import *
ImportError: No module named copy_function
```

소스를 받아온 다음, `TEST\merged.py` 를 수행해도, `TEST`폴더로 이동해서 `merged.py` 를 실행해도 오류가 납니다.

**Comment by wkim7015** [comment]
소스를 받을때 그 실행 함수들이 같은 폴더 에 없기 떄문입니다. unittest 는 external script 인지라 relative import 가 불가 합니다 ( 패키지가 아닌 모듈로 받아야 합니다: reference:  http://stackoverflow.com/questions/22942650/relative-import-from-init-py-file-throws-error).

그리고 소스를 받고 실행 시킨 결과, 전과 같은 utf-8에러 (UnicodeDecodeError)가 발견 되었습니다.

**Comment by jmhwang** [comment]
relative import  방법을 찾아보세요

`sys.path.append`  함수입니다

**Comment by jmhwang** [comment]
이 issue 를 다시 reopen 해주세요
해결된 문제가 아닙니다.

**Comment by jmhwang** [comment]
```
sys.path.append(os.path.join(os.path.dirname(__file__),".."))
혹은
sys.path.append(os.path.realpath('..'))
```

를 사용한 것을

```
sys.path.append('..')
와
sys.path.append('.')
```

를 사용하는것이 훨씬 간단해 보입니다

**Comment by jmhwang** [comment]
```

input1 = "C:\\Users\\Hojin\\Desktop\\testfile.txt"
input3 = "C:\\Users\\Hojin\\Desktop\\될까!!@!!!@!%^$#@%#^%#&.txt"
input4 = "C:\\Users\\Hojin\\Desktop\\testfiletxt"
input5 = "C:\\Users\\Hojin\\Desktop\\tEstFile2.tXT"
input6 = "C:\Users\Hojin\Desktop\\tEstFile3.tXT"
input2 = "C:\\Users\\Hojin\\Desktop\\될까.txt"

```

다른 곳에서도 테스트가 가능하도록 바꾸어 주세요

**Comment by wkim7015** [comment]
sys.path.append('..')
와
sys.path.append('.')

는 사용해본결과 불가능합니다. 이유는, 위 명령어는 다른 패키지를 만들었을떄 가능합니다.IDLE 는 intra 패키지로도 가능하지만(2.5버전 부터 가능), 도스 를 사용할때는 어느 패키지로 되지 않습니다.동시에 테스트파일이 같은 경로 안에 있기때문에, 다른 패키지로 지정이 안되어있을시, 파일명 의 정보까지 수신해야 합니다. 
reference: https://docs.python.org/2/tutorial/modules.html

**Comment by jmhwang** [comment]
merged.py 에서 `sys.path.append(os.path.join(os.path.dirname(__file__),".."))` 를 다음으로 교체

```
sys.path.append('.')
sys.path.append('..')
```

TESTlog_function.py 에서 `sys.path.append(os.path.realpath('..'))` 이것을

```
sys.path.append('..')
```

바꾸어 보시고 확인 부탁합니다.

**Comment by wkim7015** [comment]
IDLE 은 사용 가능 하나, 도스로 실행 시켰을시 importError:No module named copy_function 이 확인 됩니다.

**Comment by wkim7015** [comment]
input1 = "C:\Users\Hojin\Desktop\testfile.txt"
input3 = "C:\Users\Hojin\Desktop\될까!!@!!!@!%^$#@%#^%#&.txt"
input4 = "C:\Users\Hojin\Desktop\testfiletxt"
input5 = "C:\Users\Hojin\Desktop\tEstFile2.tXT"
input6 = "C:\Users\Hojin\Desktop\tEstFile3.tXT"
input2 = "C:\Users\Hojin\Desktop\될까.txt"

다른 곳에서도 테스트가 가능하도록 바꾸어 주세요 

: 변경 완료 했습니다. 커밋 번호는 "5d7574f" 입니다. 감사합니다
