### ISSUE TITLE
TEST의 encoding 에 문제가 있습니다.

### ISSUE THREAD

**Issue by jmhwang** [wkim7015/Back_up_0.1#4]
`#-*- coding: cp949 -*-` 라고 명기되어 있으나 실제로는 `utf8` 입니다.

**Comment by wkim7015** [comment]
윈도우의 인코딩 방식은 완성형 이라서 utf8 를 시도 해본 결과, 로그 작성시 한글이 꺠집니다. 그리고, idle 의 특정 문제인지는 모르겠으나, 특정한 한글을 조합형으로 변형시킨 결과,illegal byte exception 이 나타납니다.
e.g.
A = "갉"

# utf-8 변환 시도

 A.decode('utf-8').encode('utf-8')
결과:
 print  A.decode('utf-8').encode('utf-8')
 File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 0: invalid start byte

# cp949 시도

 print A.decode('cp949').encode('cp949')
결과:
 print A.decode('cp949').encode('cp949')
갉

cp949 의 가장 큰 단점은 한글과 영어만 지원 하기 떄문에, 다른 언어는 원래 내장되어 있는 기본 언어로 번역 할수 밖에 없습니다. 그러므로 utf 를 찾아본결과, utf-16 을 발견했습니다. 시도 해볼까요?

**Comment by wkim7015** [comment]
고쳤습니다. 감사합니다.

Commit Number: cefe269,15134db,da21084,8d09252
