### ISSUE TITLE
한글인코딩 문제

### ISSUE THREAD

**Issue by jmhwang** [wkim7015/Back_up_0.1#5]
`TESTmake_report_open_report`함수의 `path =  (input3).decode('cp949').encode('cp949')` 부분은 `path =  (input3).decode('utf8').encode('cp949')` 되어야 하는것이 아닌가요?

input3 에 들어있는 문자열은 utf8 인데요?

input3 문자열의 인코딩을 타입인 utf8 을 cp949로 바꾸겠다는 말이 아닌가요?

**Comment by wkim7015** [comment]
sys.stdin.encoding 을 사용한 결과 사용하는 파이썬 은 cp949로 내장되어있습니다. 
그래서, 강제로 utf-8 로 인코딩을 지정한다음, 시도를 해보았습니다.

  첫번째로 cp949 로 전부 문자열로 바꾼결과 unicodedecode error 가 검출 되었습니다.(decode('cp949').encode('cp949'))

두번째로 utf8로 디코딩을 한다음 cp949로 인코딩을 해보았습니다. 결과는 unicodedecode error 가 검출되었습니다.
(decode('utf-8').encode('cp949'))
두 반대의 경우에도 같은 에러가 검출되었습니다. 
문자열의 구조도 를 확인 해본결과, 아래로 되어있습니다.

cp949 ================ unicode ============ u8
                                              ============ u16
                                              ============ u32  
reference: http://egloos.zum.com/nitraqu/v/4130632

그 결과, 바로 cp949 와 utf-8은 디코딩을 다이렉트로 변환이 불가능합니다.  유니코드 라는 같은 맵을 사용해서만 변환이 가능합니다.

위 결과를 사용해, 세번째로 unicode(string).decode('cp949') 를 시도 해보았습니다. 이번에도 unicodedecode error 가 검출 되었는데, ASCII 에러 또한 발견했습니다.

그러므로, cp949 의 변환 용량이 utf8 보다 작기때문에, 파이썬의 unicode 사용량, 즉 ASCII 코드 저장량 이 전체 utf-8 의 unicode 사용량 과 같지 않다는것 을 추론할 수 있습니다.

이 문제를 해결할려면, 저의 생각으로는 외부의 일대일 대응 의 라이브러리를 찾아서 컨버전의 방법, 변환 불가인 ASCII 코드는 무시하는 방법  또는 윈도우도 cp949 를 사용한다는 정보하에 텍스트로 모든 파라메터 및 인풋을 전달한다음 다시 가지고 와서 하나씩 읽는 방법이 있다고 생각합니다. 물론 유니코드 에러는 다른 os 에서는 검출 되지 않을 가능성이 있습니다.

**Comment by wkim7015** [comment]
TESTUTF-8 으로 새로 만들었습니다. 커밋 번호는 68135d1 입니다. 감사합니다
